import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Example #1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to my home page</h1>
        <ul>
          <li>Create</li>
          <li>Read</li>
          <li>Update</li>
          <li>Delete</li>
        </ul>

        <Link href="/about">
          <h2>About Page</h2>
        </Link>

        <Link href="/grades">
          <h2>Grades Page</h2>
        </Link>

        <button>View all this info</button>

        <footer>In Class Example #1</footer>

      </main>



    </>
  )
}
